cart_pole_controller:
  ros__parameters:
    type: velocity_controllers/JointGroupVelocityController
    joints:
       - slider_to_cart
    write_op_modes:
       - slider_to_cart

joint_state_controller:
  ros__parameters:
    type: joint_state_controller/JointStateController
