controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    joint_state_controller:
      type: joint_state_controller/JointStateController

velocity_controller:
  ros__parameters:
    joints:
      - slider_to_cart
