name: Check Docs

on:
  workflow_dispatch:
  pull_request:

jobs:
  check-docs:
    name: Check Docs
    uses: ros-controls/control.ros.org/.github/workflows/reusable-sphinx-check-single-version.yml@master
    with:
      GAZEBO_ROS2_CONTROL_PR: ${{ github.ref }}
